'use strict';

/**
 * Connection + message rate limits for WebSocket.
 *
 * Env (optional):
 *   BP_WS_CONN_LIMIT   — max new connections per IP per window (default 40)
 *   BP_WS_CONN_WINDOW  — window ms (default 10000)
 *   BP_WS_MSG_LIMIT    — max messages per socket per window (default 60)
 *   BP_WS_MSG_WINDOW   — window ms (default 1000)
 *
 * HTTP auth throttling (login / check-login / register / delete / admin):
 *   BP_AUTH_IP_FAILS     — failed attempts per IP per window (default 30)
 *   BP_AUTH_IP_WINDOW    — window ms (default 600000 = 10 min)
 *   BP_AUTH_PAIR_FAILS   — failures per IP+login pair per window (default 8)
 *   BP_AUTH_LOGIN_FAILS  — failures per login from ALL IPs per window (default 100)
 *   BP_AUTH_LOGIN_WINDOW — window ms for the two above (default 900000 = 15 min)
 *   BP_AUTH_DEVICE_FAILS — failures per device id per BP_AUTH_IP_WINDOW (default 15)
 *   BP_REGISTER_LIMIT    — registrations per IP per hour (default 20)
 *   BP_REGISTER_DEVICE_LIMIT — registrations per device id per hour (default 5)
 *
 * Every limit is tracked per device id (X-Device-Id / bp_device_id cookie) AND per IP.
 * The device id is generated by the client, so it identifies a browser profile and can be
 * rotated by an attacker; the IP limits stay as the backstop for that case.
 */

const CONN_LIMIT = Math.max(5, Number(process.env.BP_WS_CONN_LIMIT) || 40);
const CONN_WINDOW = Math.max(1000, Number(process.env.BP_WS_CONN_WINDOW) || 10000);
const MSG_LIMIT = Math.max(10, Number(process.env.BP_WS_MSG_LIMIT) || 60);
const MSG_WINDOW = Math.max(200, Number(process.env.BP_WS_MSG_WINDOW) || 1000);

/** @type {Map<string, { t0: number, n: number }>} */
const _connHits = new Map();

/**
 * Per-IP connection rate limit (new WS handshakes).
 * @param {string} ip
 * @returns {boolean} true if allowed
 */
function allowWsConnection(ip) {
  const key = ip || 'unknown';
  const now = Date.now();
  let e = _connHits.get(key);
  if (!e || now - e.t0 > CONN_WINDOW) {
    e = { t0: now, n: 0 };
    _connHits.set(key, e);
  }
  e.n += 1;
  // periodic cleanup
  if (_connHits.size > 5000) {
    for (const [k, v] of _connHits) {
      if (now - v.t0 > CONN_WINDOW * 3) _connHits.delete(k);
    }
  }
  return e.n <= CONN_LIMIT;
}

/**
 * Per-socket message rate limit (all inbound messages).
 * Place moves have additional server-side limits inside MatchRoom.
 * @param {import('ws').WebSocket & { _msgWindow?: { t0: number, n: number }, _rlDrops?: number }} ws
 * @returns {boolean} true if allowed
 */
function allowWsMessage(ws) {
  const now = Date.now();
  if (!ws._msgWindow || now - ws._msgWindow.t0 > MSG_WINDOW) {
    ws._msgWindow = { t0: now, n: 0 };
  }
  ws._msgWindow.n += 1;
  if (ws._msgWindow.n > MSG_LIMIT) {
    ws._rlDrops = (ws._rlDrops | 0) + 1;
    return false;
  }
  return true;
}

/**
 * Fixed-window counter keyed by string, with bounded memory.
 * @param {number} limit
 * @param {number} windowMs
 */
function createWindowCounter(limit, windowMs) {
  /** @type {Map<string, { t0: number, n: number }>} */
  const map = new Map();
  function prune(now) {
    if (map.size < 5000) return;
    for (const [k, v] of map) {
      if (now - v.t0 > windowMs) map.delete(k);
    }
    // Hard cap: under a flood of unique keys drop the oldest entries.
    if (map.size > 50000) {
      let drop = map.size - 40000;
      for (const k of map.keys()) {
        map.delete(k);
        if (--drop <= 0) break;
      }
    }
  }
  function live(key, now) {
    const e = map.get(key);
    if (!e) return null;
    if (now - e.t0 > windowMs) { map.delete(key); return null; }
    return e;
  }
  return {
    limit,
    windowMs,
    /** Record one event; returns the new count in the current window. */
    hit(key, now) {
      now = now || Date.now();
      let e = live(key, now);
      if (!e) {
        prune(now);
        e = { t0: now, n: 0 };
        map.set(key, e);
      }
      e.n += 1;
      return e.n;
    },
    /** True when the key has already reached the limit. */
    blocked(key, now) {
      const e = live(key, now || Date.now());
      return !!e && e.n >= limit;
    },
    /** Seconds until the window of this key resets (0 when not tracked). */
    retryAfterSec(key, now) {
      now = now || Date.now();
      const e = live(key, now);
      return e ? Math.max(1, Math.ceil((e.t0 + windowMs - now) / 1000)) : 0;
    },
    reset(key) { map.delete(key); },
    clear() { map.clear(); },
    get size() { return map.size; }
  };
}

function envInt(name, def, min) {
  const n = Number(process.env[name]);
  return Math.max(min || 1, Number.isFinite(n) && n > 0 ? Math.floor(n) : def);
}

/**
 * Brute-force protection for password endpoints.
 * Failures are counted three ways so that neither a single IP nor a botnet can
 * grind one account, while one attacker cannot lock a victim out from every IP
 * (the per-login ceiling is much higher than the per-pair one).
 */
function createAuthLimiter(opts) {
  opts = opts || {};
  const ipWindow = opts.ipWindow || envInt('BP_AUTH_IP_WINDOW', 600000, 1000);
  const loginWindow = opts.loginWindow || envInt('BP_AUTH_LOGIN_WINDOW', 900000, 1000);
  const pairLimit = opts.pairFails || envInt('BP_AUTH_PAIR_FAILS', 8);
  const ipFails = createWindowCounter(opts.ipFails || envInt('BP_AUTH_IP_FAILS', 30), ipWindow);
  const pairFails = createWindowCounter(pairLimit, loginWindow);
  const loginFails = createWindowCounter(opts.loginFails || envInt('BP_AUTH_LOGIN_FAILS', 100), loginWindow);
  // Same checks keyed by device id (primary identity of a player's browser).
  const devFails = createWindowCounter(opts.deviceFails || envInt('BP_AUTH_DEVICE_FAILS', 15), ipWindow);
  const devPairFails = createWindowCounter(pairLimit, loginWindow);
  const registers = createWindowCounter(
    opts.registerLimit || envInt('BP_REGISTER_LIMIT', 20),
    opts.registerWindow || 3600000);
  const devRegisters = createWindowCounter(
    opts.registerDeviceLimit || envInt('BP_REGISTER_DEVICE_LIMIT', 5),
    opts.registerWindow || 3600000);

  const norm = (s) => String(s == null ? '' : s).trim().toLowerCase().slice(0, 64);
  const dev = (d) => String(d == null ? '' : d).slice(0, 64);

  return {
    /**
     * @param {string} ip
     * @param {string} [login]
     * @param {string} [deviceId]
     * @returns {{ ok: boolean, retryAfter: number }}
     */
    check(ip, login, deviceId) {
      const l = norm(login);
      const d = dev(deviceId);
      const hits = [];
      if (ipFails.blocked(ip)) hits.push([ipFails, ip]);
      if (l && pairFails.blocked(ip + '|' + l)) hits.push([pairFails, ip + '|' + l]);
      if (l && loginFails.blocked(l)) hits.push([loginFails, l]);
      if (d && devFails.blocked(d)) hits.push([devFails, d]);
      if (d && l && devPairFails.blocked(d + '|' + l)) hits.push([devPairFails, d + '|' + l]);
      if (!hits.length) return { ok: true, retryAfter: 0 };
      return { ok: false, retryAfter: Math.max.apply(null, hits.map(([c, k]) => c.retryAfterSec(k))) };
    },
    fail(ip, login, deviceId) {
      ipFails.hit(ip);
      const l = norm(login);
      const d = dev(deviceId);
      if (l) { pairFails.hit(ip + '|' + l); loginFails.hit(l); }
      if (d) { devFails.hit(d); if (l) devPairFails.hit(d + '|' + l); }
    },
    success(ip, login, deviceId) {
      const l = norm(login);
      const d = dev(deviceId);
      if (l) pairFails.reset(ip + '|' + l);
      if (d && l) devPairFails.reset(d + '|' + l);
    },
    /** Registration flood guard (counts every attempt), per IP and per device. */
    checkRegister(ip, deviceId) {
      const d = dev(deviceId);
      const hits = [];
      if (registers.blocked(ip)) hits.push([registers, ip]);
      if (d && devRegisters.blocked(d)) hits.push([devRegisters, d]);
      if (!hits.length) return { ok: true, retryAfter: 0 };
      return { ok: false, retryAfter: Math.max.apply(null, hits.map(([c, k]) => c.retryAfterSec(k))) };
    },
    registerHit(ip, deviceId) {
      registers.hit(ip);
      const d = dev(deviceId);
      if (d) devRegisters.hit(d);
    },
    clear() {
      ipFails.clear(); pairFails.clear(); loginFails.clear();
      devFails.clear(); devPairFails.clear(); registers.clear(); devRegisters.clear();
    }
  };
}

module.exports = {
  createWindowCounter,
  createAuthLimiter,
  allowWsConnection,
  allowWsMessage,
  CONN_LIMIT,
  CONN_WINDOW,
  MSG_LIMIT,
  MSG_WINDOW
};
